import * as dotenv from "dotenv";
import { SurrealDBManager } from "../database/SurrealDBManager";

dotenv.config();

async function testAutoGeneratedId() {
	const db = new SurrealDBManager();

	try {
		await db.connect();
		console.log("🔹 Connected to database");

		// Test inserting a message without specifying id
		console.log("🔹 Testing INSERT without id (auto-generated)...");
		try {
			const result = await db.db.query(`
				INSERT INTO messages (channel_id, guild_id, author_id, content, timestamp, attachments, embeds, created_at, updated_at, active)
				VALUES ('1430111461547446402', '1254694808228986912', '99195129516007424', 'Auto-generated ID test', '${new Date().toISOString()}', [], [], '${new Date().toISOString()}', '${new Date().toISOString()}', true)
			`);
			console.log("🔹 Insert result:", result);
		} catch (error) {
			console.log("🔸 Insert failed:", error.message);
		}

		// Test inserting another message
		console.log("🔹 Testing second INSERT...");
		try {
			const result = await db.db.query(`
				INSERT INTO messages (channel_id, guild_id, author_id, content, timestamp, attachments, embeds, created_at, updated_at, active)
				VALUES ('1430111461547446402', '1254694808228986912', '99195129516007424', 'Second auto-generated ID test', '${new Date().toISOString()}', [], [], '${new Date().toISOString()}', '${new Date().toISOString()}', true)
			`);
			console.log("🔹 Second insert result:", result);
		} catch (error) {
			console.log("🔸 Second insert failed:", error.message);
		}

		// Query all messages
		console.log("🔹 Querying all messages...");
		try {
			const allMessages = await db.db.query("SELECT * FROM messages");
			console.log(
				"🔹 All messages count:",
				allMessages[0]?.result?.length || 0,
			);
			console.log("🔹 All messages:", allMessages[0]?.result);
		} catch (error) {
			console.log("🔸 Query failed:", error.message);
		}

		// Count messages
		console.log("🔹 Counting messages...");
		try {
			const countResult = await db.db.query("SELECT count() FROM messages");
			console.log(
				"🔹 Message count:",
				countResult[0]?.result?.[0]?.["count()"] || 0,
			);
		} catch (error) {
			console.log("🔸 Count failed:", error.message);
		}

		// Test querying by guild_id
		console.log("🔹 Querying by guild_id...");
		try {
			const guildMessages = await db.db.query(
				"SELECT * FROM messages WHERE guild_id = '1254694808228986912'",
			);
			console.log(
				"🔹 Guild messages count:",
				guildMessages[0]?.result?.length || 0,
			);
		} catch (error) {
			console.log("🔸 Guild query failed:", error.message);
		}
	} catch (error) {
		console.error("🔸 Error:", error);
	} finally {
		await db.disconnect();
		console.log("🔹 Disconnected");
	}
}

testAutoGeneratedId().catch(console.error);
